title: yufeng Lv's Homepage
page-top-title: yufeng Lv
top-section-bg-text: Be what you wanna be
home-subtitle: yufeng Lv&ensp;|&ensp;吕玉凤
email: "minionlove@163.com"
copyright-text: '&copy; yufeng Lv 2023-2025. All Rights Reserved.'